/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xerdi_jkpathsea_KPathSea */

#ifndef _Included_com_xerdi_jkpathsea_KPathSea
#define _Included_com_xerdi_jkpathsea_KPathSea
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xerdi_jkpathsea_KPathSea_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    setProgramName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xerdi_jkpathsea_KPathSea_setProgramName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    findFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xerdi_jkpathsea_KPathSea_findFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xerdi_jkpathsea_KPathSea_nativeCleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
