/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xerdi_jkpathsea_KPathSea */

#ifndef _Included_com_xerdi_jkpathsea_KPathSea
#define _Included_com_xerdi_jkpathsea_KPathSea
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xerdi_jkpathsea_KPathSea_init
  (JNIEnv *, jobject);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xerdi_jkpathsea_KPathSea_version
  (JNIEnv *, jobject);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    set_program_name
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xerdi_jkpathsea_KPathSea_set_1program_1name
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    find_file
 * Signature: (JLjava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xerdi_jkpathsea_KPathSea_find_1file
  (JNIEnv *, jobject, jlong, jstring, jint, jboolean);

/*
 * Class:     com_xerdi_jkpathsea_KPathSea
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xerdi_jkpathsea_KPathSea_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
